spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///huali?useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        format_sql: true
        show_sql: true
      
  thymeleaf:
    cache: false